<?php
session_start();
unset($_SESSION["lesson"]);
unset($_SESSION["progress"]);
unset($_SESSION["mistakes"]);
unset($_SESSION["lesson_count"]);
unset($_SESSION["lesson_time"]);
unset($_SESSION["current_time"]);
unset($_SESSION["fail"]);
?>